export type {
  RegisterRequest,
  LoginRequest,
  GuestJudgeRequest,
  EventRequest,
  CategoryRequest,
  RoundRequest,
  TeamCreateRequest,
  SubmissionRequest,
  ScoreRequest,
  AwardRequest,
  UserProfileResponse,
  EventDTO,
  TeamDTO,
  SubmissionDTO,
  ScoreDTO,
  LeaderboardEntry,
  NotificationDTO,
} from "@/lib/api/hackathonApi";
